# f - format string

#1 to 100 - Hyphen Separated
for i in range(1,101):
    print(f"{i}-", end='')

print("\n ")
hyphen_separated_numbers = '-'.join(map(str, range(1, 101)))
print(hyphen_separated_numbers)




#----------code explanation-------
"""
map(str, ...):

The map function applies a given function (in this case, str) to all items in an iterable (in this case, the sequence of numbers generated by range(1, 101)).
str converts each number to a string. So, map(str, range(1, 101)) results in an iterable of the numbers 1 through 100, but as strings.

'-'.join(...):

The join method takes an iterable (such as a list) of strings and concatenates them into a single string, with each element separated by the string that join was called on. Here, '-' is the separator.
'-'.join(map(str, range(1, 101))) joins all the string representations of the numbers with a hyphen (-) between them.
"""

# -------- map  function ------------


# Define a function that takes a number and returns its square
print("\n")
def square(x):
    return x**2

# Create a list of numbers
numbers = [1, 2, 3, 4, 5]

# Use the map function to apply the square function to each element of the list
# The map function returns an iterator object, so we need to convert it to a list
squares = list(map(square, numbers))

# Print the list of squares
print(squares)
# Output: [1, 4, 9, 16, 25]

# ------- join function ------
words = ["apple", "banana", "cherry"]
separator = ", "
result = separator.join(words)
print(result) # Output: apple, banana, cherry